Scripts/BuildAndTest.cmd, Src/RE2.Managed/RE2.Managed.csproj, Src/SarifPatternMatcher/SarifPatternMatcher.csproj, Src/SarifPatternMatcher/Validation.cs, Src/String8/String8.csproj, Src/Test.UnitTests.SarifPatternMatcher/AnalyzeCommandTests.cs, Src/Test.UnitTests.SarifPatternMatcher/TestAnalyzeCommand.cs, Targets/build.common.props, Targets/build.product.props
@eddynaka 
These changes are required for this repo to itself be embedded as a submodule in another repo.
=> Update props references to work against referencing project file.

Src/SarifPatternMatcher/AnalyzeCommand.cs, Src/Test.UnitTests.SarifPatternMatcher/AnalyzeCommandTests.cs
=> Sarif sdk update

Src/.ruleset, Src/Plugins/PlaintextSecrets/AzureDevOpsPersonalAccessTokenValidator.cs, Src/Plugins/PlaintextSecrets/PlaintextSecrets.json, Src/Plugins/PlaintextSecrets/ValidationState.cs, Src/RE2.Managed/NativeMethods.cs, Src/RE2.Managed/Regex2.cs, Src/RE2.Managed/Timeout.cs, Src/SarifPatternMatcher/AnalyzeCommand.cs, Src/SarifPatternMatcher/AnalyzeContext.cs, Src/SarifPatternMatcher/AnalyzeOptions.cs, Src/SarifPatternMatcher/SearchSkimmer.cs, Src/SarifPatternMatcher/Validation.cs, Src/SarifPatternMatcher/ValidatorsCache.cs
=> Provide enanced dynamic validation capability.

Src/SarifPatternMatcher.runsettings, Src/SarifPatternMatcher.sln, Targets/build.test.props
=> Moving TestResults to bld folder

Src/SarifPatternMatcher/SearchSkimmer.cs
Passing context file contents into the region population helper. Fixing the issue identified during consumption.
=> Passing context file contents into the region population helper.

Src/Plugins/PlaintextSecrets/PlaintextSecrets.json, Src/Plugins/Test.FunctionalTests.AllPlugins/TestData/PlaintextSecrets/ExpectedOutputs/VariousPats.sarif, Src/Plugins/Test.FunctionalTests.AllPlugins/TestData/PlaintextSecrets/Inputs/VariousPats.txt, Src/SarifPatternMatcher.Cli/SarifPatternMatcher.Cli.csproj, Src/SarifPatternMatcher/SearchSkimmer.cs
=> Add base64 decoding of static analysis checks.

.gitignore, Src/Plugins/Security/Security.csproj
=> Copying .spam to sln and fixing targets

Src/Sarif.PatternMatcher/SearchSkimmer.cs
@eddynaka merge if you agree. :)
=> Provide string.empty instead of null in args list.

Src/Sarif.PatternMatcher/Sarif.PatternMatcher.csproj
=> Update to newtonsoft 12.0.3

Src/Plugins/Tests.Security/Validators/AzureDevOpsPersonalAccessTokenValidatorTests.cs, Src/Sarif.PatternMatcher.Benchmark/Benchmarks/AnalyzeCommandBenchmarks.cs
=> Fact over theory

Src/Plugins/Utilities.cs, Targets/build.plugins.props
=> Add utilities class for validation plugins.

Src/Sarif.PatternMatcher/SearchSkimmer.cs
=> Adjust failure level appropriately when dynamic validation is in play.

Src/Sarif.PatternMatcher/SearchSkimmer.cs
=> Correct fingerprint regions

Src/Plugins/Security/AzureDevOpsPersonalAccessTokenValidator.cs, Src/Plugins/Tests.Security/Validators/AzureDevOpsPersonalAccessTokenValidatorTests.cs, Src/RE2.Managed/FlexMatch.cs, Src/RE2.Managed/IRegex.cs, Src/RE2.Managed/RE2Regex.cs, Src/RE2.Managed/RegexDefaults.cs, Src/Sarif.PatternMatcher.Benchmark/Benchmarks/AnalyzeCommandBenchmarks.cs, Src/Sarif.PatternMatcher/AnalyzeCommand.cs, Src/Sarif.PatternMatcher/CachedDotNetRegex.cs, Src/Sarif.PatternMatcher/DotNetRegex.cs, Src/Sarif.PatternMatcher/SearchSkimmer.cs, Src/Sarif.PatternMatcher/ValidatorsCache.cs, Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs, Src/Test.UnitTests.Sarif.PatternMatcher/SearchSkimmerTests.cs
@eddynaka, FYI. Happy New Year! Feliz 2021!
=> Match refinement

Src/Sarif.PatternMatcher/AnalyzeOptions.cs
@eddynaka  update SARIF to main.
=> Update SARIF submodule.

Src/Plugins/Fingerprint.cs, Src/Plugins/Tests.Security/TestData/ReviewPotentiallySensitiveData/ExpectedOutputs/SocialSecurityNumbers.sarif, Src/Plugins/Tests.Security/TestData/ReviewPotentiallySensitiveFiles/ExpectedOutputs/Fake.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/VariousPats.sarif, Src/Plugins/Tests.Security/TestData/UseSecureApi/ExpectedOutputs/Malloc.sarif, Src/Plugins/ValidationState.cs, Src/Plugins/ValidatorBase.cs, Src/Sarif.PatternMatcher/AnalyzeContext.cs, Src/Sarif.PatternMatcher/AnalyzeOptions.cs, Src/Sarif.PatternMatcher/SearchSkimmer.cs, Src/Sarif.PatternMatcher/Validation.cs, Src/Sarif.PatternMatcher/ValidatorsCache.cs, Src/Test.UnitTests.Sarif.PatternMatcher/SearchSkimmerTests.cs, Targets/build.plugins.props
=> Fingerprints and multiline rules

Src/Sarif.PatternMatcher/SearchSkimmer.cs
@eddynaka, minor update to user-facing string.
=> tweak host unknown message to report against resource.

Src/Sarif.PatternMatcher/Fingerprint.cs, Src/Sarif.PatternMatcher/ValidatorsCache.cs
Minor fixes in support of new fingerprinting.
@eddynaka
=> Add SPAM fixes

Src/Plugins/Security/EmailAddressValidator.cs, Src/Plugins/Security/SEC1002.ReviewPotentiallySensitiveData.json, Src/Plugins/Tests.Security/TestData/ReviewPotentiallySensitiveData/ExpectedOutputs/SEC1002.EmailAddress_with_email_addresses.sarif, Src/Plugins/Tests.Security/TestData/ReviewPotentiallySensitiveData/Inputs/SEC1002.EmailAddress_with_email_addresses.txt, Src/Sarif.PatternMatcher/Fingerprint.cs, Src/Sarif.PatternMatcher/ValidatorsCache.cs
Fixes #100
Update regex, add validator, add test cases, update expected output
=> Update regex, add validator, add test cases, update expected output

Src/Plugins/ValidatorBase.cs, Src/Sarif.PatternMatcher/AnalyzeOptions.cs, Src/Sarif.PatternMatcher/Fingerprint.cs
=> Add elements to fingerprint. Increase visibility on shared code.

Src/Sarif.PatternMatcher/Fingerprint.cs
=> Do not emit empty fingerprint components.

Src/Sarif.PatternMatcher/SearchSkimmer.cs
=> Update validation message.

Src/Sarif.PatternMatcher/MatchExpression.cs, Src/Sarif.PatternMatcher/SearchSkimmer.cs
=> Allow for flowing rule properties to rules.

Src/Plugins/Security/AdoPatValidator.cs, Src/Plugins/Security/GitHubPatValidator.cs, Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_006.GitHubPat.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_102.AdoPat.sarif, Src/Sarif.PatternMatcher/Fingerprint.cs, Src/Sarif.PatternMatcher/SearchSkimmer.cs, Src/Sarif.PatternMatcher/ValidatingVisitor.cs
=> Simplify pat fingerprint name

Src/Plugins/Security/GitHubAppCredentialsValidator.cs, Src/Plugins/Security/GitHubPatValidator.cs, Src/Plugins/Security/GoogleApiKeyValidator.cs, Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Security/Security.csproj, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_003.GoogleApiKey.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_003.GoogleApiKey.txt, Src/Plugins/Tests.Security/Tests.Security.csproj, Src/Plugins/ValidatorBase.cs
=> Google API key validator.

Src/Plugins/ValidatorBase.cs
@eddynaka 
This utility code does a thorough job of looking around for unknown host exception messages.
=> Clean up exception reporting utility code.

Src/Plugins/ValidatorBase.cs
=> Exception handling

Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_006.GitHubPat.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_006.GitHubPat.txt
=> Gh noise reduction

Src/Sarif.PatternMatcher/ValidatorsCache.cs
=> Don't pass Expired creds to validators

Src/Sarif.PatternMatcher.Cli/App.config
=> Add general Newtonsoft binding redirect.

Src/Plugins/Security/SEC101_006.GitHubPatValidator.cs, Src/Plugins/Security/SEC101_007.GitHubAppCredentialsValidator.cs, Src/Sarif.PatternMatcher/AnalyzeCommand.cs
=> Add comments and improve assert for unexpanded shared string.

Src/Sarif.PatternMatcher/AnalyzeCommand.cs
=> Improve unexpanded assert reporting.

Src/Plugins/ValidatorBase.cs
=> Render SSL/TLS error as unknown host.

Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_006.GitHubPat.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_007.GitHubAppCredentials.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_008.AwsCredentials.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_045.PostgreSqlConnectionString.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_046.SqlConnectionString.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_047.MySqlConnectionString.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_006.GitHubPat.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_007.GitHubAppCredentials.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_008.AwsCredentials.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_045.PostgreSqlConnectionString.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_046.SqlConnectionString.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_047.MySqlConnectionString.ps1, Src/Plugins/ValidatorBase.cs, Src/Sarif.PatternMatcher/SearchSkimmer.cs
We will only fire a single result per file, per fingerprint. This helps eliminate noise due to over-aggressive regex matching.
@eddynaka @jameswinkler
=> Static analysis caching

Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/SEC101_008.AwsCredentialsValidator.cs, Src/Plugins/Security/SEC101_024.SendGridApiKeyValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_024.SendGridApiKey.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_024.SendGridApiKey.txt, Src/Plugins/Tests.Security/Tests.Security.csproj
=> Add SendGrid dynamic validator.

Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/SEC101_023.AmazonMwsAuthTokenValidator.cs, Src/Plugins/Security/SEC101_031.NuGetApiKeyValidator.cs, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_031.NuGetApiKey.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_031.NuGetApiKey.txt, Src/Plugins/Tests.Security/Tests.Security.csproj
=> Add NuGet test files.

Src/Plugins/ValidatorBase.cs
Add utility for generating a normalized specific shannon entropy metric for a given string of a given total symbol set.
=> Shannon entropy

Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/SEC101_010.SquarePatValidator.cs, Src/Plugins/Security/SEC101_011.SquareCredentialsValidator.cs, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_010.SquarePat.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_011.SquareCredentials.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_010.SquarePat.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_011.SquareCredentials.ps1
- Merge SquareId with SquareKey into SquareCredentials
- Enable SquarePatValidator
- Remove old Square rules
=> Enable Square fingerprint

Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/SEC101_012.SlackWebhookValidator.cs, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_012.SlackWebhook.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_012.SlackWebhook.txt, Src/Plugins/Tests.Security/Tests.Security.csproj, Src/Plugins/ValidatorBase.cs
=> Add Slack incoming webhook detection and validator.

Src/Plugins/Security/SEC101_013.CryptographicPrivateKeyValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_013.CryptographicPrivateKey.txt
=> Add handling for empty certificate key data.

Src/Plugins/Security/SEC101_003.GoogleApiKeyValidator.cs
Rverting this pr: https://github.com/microsoft/sarif-pattern-matcher/pull/218
=> ProjectNotAuthorized should be NoMatch

Src/Plugins/Security/SEC101_001.HttpAuthorizationRequestHeaderValidator.cs, Src/Plugins/Security/SEC101_005.SlackTokenValidator.cs, Src/Plugins/Security/SEC101_045.PostgreSqlConnectionStringValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_046.SqlConnectionString.sarif
- Improved false positives for httpauthorization
- Fixed wrong response.error usage in slack validator
- Ignoring tcp connections from postgres validator
- improving postgres exception logging (first inner then exception if exists)
=> Improving validators

Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_004.FacebookAppCredentials.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_004.FacebookAppCredentials.ps1
=> Adding more tests to facebookAppCredentials

Src/Plugins/Security/SEC101_036.MySqlConnectionStringValidator.cs
- with this change, we would also try to validate connections without database
=> Improving MySql validator

Src/Plugins/Security/SEC101_036.MySqlConnectionStringValidator.cs, Src/Plugins/Security/SEC101_037.SqlConnectionStringValidator.cs, Src/Plugins/Security/SEC101_038.PostgreSqlConnectionStringValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_036.MySqlConnectionString.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_037.SqlConnectionString.sarif, Src/RE2.Managed/FlexMatch.cs, Src/RE2.Managed/RE2Regex.cs, Src/RE2.Managed/Regex2.cs, Src/Sarif.PatternMatcher.Sdk/ValidatorBase.cs, Src/Sarif.PatternMatcher/ValidatorsCache.cs
=> Sarif update

Src/Plugins/Security/Security.SharedStrings.txt
Left side = Previous
Right side = After change
Removing unnamed groups would allocate less strings, ints, bools.
Without allocating those, we would call less times GC, with that GC would affect less the runtime of the analysis
=> Removing unnamed groups

Src/Plugins/Security/SEC101_037.SqlConnectionStringValidator.cs, Src/Plugins/Security/SEC101_038.PostgreSqlConnectionStringValidator.cs, Src/Sarif.PatternMatcher/AnalyzeCommand.cs, Src/Sarif.PatternMatcher/SearchSkimmer.cs, Src/Sarif.PatternMatcher/ValidatorsCache.cs, Src/Test.UnitTests.Sarif.PatternMatcher.Cli/AnalyzeCommandTests.cs, Src/Test.UnitTests.Sarif.PatternMatcher/ValidatorsCacheTests.cs
@eddynaka, hey, look at this! an engine change that comes in first with testing. :)
as a next step, I will re-author a single-line, multicomponent rule, wanted you to get this first look.
=> Author single-line, multicomponent analysis.

Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/SEC101_036.MySqlConnectionStringValidator.cs, Src/Plugins/Security/SEC101_037.SqlConnectionStringValidator.cs, Src/Plugins/Security/SEC101_038.PostgreSqlConnectionStringValidator.cs, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Security/Utilities/FilteringHelpers.cs, Src/Plugins/Tests.Security/EndToEndTests.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_037.SqlConnectionString.sarif, Src/Sarif.PatternMatcher/AnalyzeCommand.cs, Src/Test.UnitTests.Sarif.PatternMatcher.Cli/AnalyzeCommandTests.cs, Src/Test.UnitTests.Sarif.PatternMatcher.Cli/SharedStrings.txt, Src/Test.UnitTests.Sarif.PatternMatcher.Cli/Test.UnitTests.Sarif.PatternMatcher.Cli.csproj
@eddynaka, review all my notes on this one, lots of subtleties to discuss. :)
=> Sql singleline

Src/Plugins/Security/SEC101_036.MySqlCredentialsValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_036.MySqlCredentials.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_036.MySqlCredentials.ps1, Src/Sarif.PatternMatcher/SharedUtilities.cs, Src/Test.UnitTests.Sarif.PatternMatcher/SharedUtilitiesTests.cs
Makes a fix so that Azure MySQL DB matches that won't be well-formed are not attempted dynamically.
=> Fix MySQL to properly handle Azure hosts.

Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_031.NuGetApiKey.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_031.NuGetApiKey.txt
=> Nuget refinement

Src/Plugins/Security/SEC101_011.SquareCredentialsValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_011.SquareCredentials.sarif, Src/Plugins/Tests.Security/Tests.Security.csproj, Src/Plugins/Tests.Security/Validators/SEC101_011 - SquareCredentialsValidatorTests.cs, Src/Plugins/Tests.Security/Validators/SEC101_011.SquareCredentialsValidatorTests.cs, Src/Sarif.PatternMatcher.Sdk/ValidatorBase.cs, docs/Rules.md
* Adds a Dynamic Stripe Validator
* Adds a DynamicStripeValidatopr_Test class as well.
=> Add Square Credentials Dynamic Validator

Src/Plugins/Security/SEC101_046.DiscordApiCredentialsValidator.cs, Src/Plugins/Tests.Security/Validators/SEC101_046.DiscordApiCredentialsValidatorTests.cs
Tests all return paths of the call.
=> Add mock http calls to DiscordValidatorTests

Src/Plugins/Security/SEC101_047.CratesApiKeyValidator.cs, Src/Plugins/Tests.Security/Validators/SEC101_047.CratesApiKeyValidatorTests.cs
=> Improving CratesApiKey validator

Src/Plugins/Security/SEC101_003.GoogleApiKeyValidator.cs, Src/Plugins/Security/SEC101_005.SlackTokenValidator.cs, Src/Plugins/Security/SEC101_006.GitHubPatValidator.cs, Src/Plugins/Security/SEC101_014.FacebookAccessTokenValidator.cs, Src/Plugins/Security/SEC101_016.StripeApiKeyValidator.cs, Src/Plugins/Security/SEC101_017.NpmAuthorTokenValidator.cs, Src/Plugins/Security/SEC101_019.PicaticApiKeyValidator.cs, Src/Plugins/Security/SEC101_020.DropboxAccessTokenValidator.cs, Src/Plugins/Security/SEC101_022.PayPalBraintreeAccessTokenValidator.cs, Src/Plugins/Security/SEC101_023.AmazonMwsAuthTokenValidator.cs, Src/Plugins/Security/SEC101_024.TwilioApiKeyValidator.cs, Src/Plugins/Security/SEC101_027.MailChimpApiKeyValidator.cs, Src/Plugins/Security/SEC101_028.PlaintextPasswordValidator.cs, Src/Plugins/Security/SEC101_030.GoogleServiceAccountKeyValidator.cs, Src/Plugins/Security/SEC101_031.NuGetApiKeyValidator.cs, Src/Plugins/Security/SEC101_032.GpgCredentialsValidator.cs, Src/Plugins/Security/SEC101_039.ShopifyAccessTokenValidator.cs, Src/Plugins/Security/SEC101_040.ShopifySharedSecretValidator.cs, Src/Plugins/Security/SEC101_042.DynatraceTokenValidator.cs, Src/Plugins/Security/SEC101_045.PostmanApiKeyValidator.cs, Src/Plugins/Security/SEC101_102.AdoPatValidator.cs, Src/Plugins/Tests.Security/Validators/SEC101_102.AdoPatValidatorTests.cs, Src/ReleaseHistory.md, Src/Sarif.PatternMatcher/ValidatorsCache.cs
=> Removing redundant TryGetNonEmptyValue when key is required

Src/Plugins/Tests.SalModernization/TestData/UpdateSalToCurrentVersion/ExpectedOutputs/SEC105_001.AnalysisAssume.sarif, Src/ReleaseHistory.md, Src/Sarif.PatternMatcher/SearchSkimmer.cs
=> Tool should emit fixes with comprehensive region properties

Src/Plugins/Tests.Security/Validators/SEC101_020.DropboxAccessTokenTokenValidatorTests.cs
Create Dynamic validator Test for Dropbox Access Token
=> Create Dynamic validator Test for Dropbox Access Token

Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_041.RabbitMqCredentials.ps1, Src/ReleaseHistory.md
=> Improving RabbitMQ regex (removing new lines and spaces) from secret

Src/Plugins/Tests.Security/Validators/SEC101_010.SquarePatValidatorTests.cs, Src/Plugins/Tests.Security/Validators/SEC101_011.SquareCredentialsValidatorTests.cs
Updates Square Credentials and PAT tests to use the global struct.
=> Improve Square Mock Tests

Src/Plugins/Security/Security.SharedStrings.txt, Src/ReleaseHistory.md
This is a follow-up PR from #548 to normalize regular expressions that contain both `\n` and `\s`. 
=> Normalizing regex (\n\s => \s)

Src/Plugins/Security/SEC101_018.TwilioCredentialsValidator.cs, Src/Plugins/Tests.Security/Validators/SEC101_018.TwilioCredentialsValidatorTests.cs, Src/ReleaseHistory.md
=> Improving twilio dynamic validator for test credentials

Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_036.MySqlCredentials.ps1, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_041.RabbitMqCredentials.ps1, Src/ReleaseHistory.md
=> Improving regex for MySql, Postgres and RabbitMQ

Src/ReleaseHistory.md
- Updating previous releases adding the `NR` (New Rule) entry
- Adding releases that weren't in the markdown file
=> Updating ReleaseHistory backfilling previous releases

Src/Plugins/Security/SEC101_025.SendGridApiKeyValidator.cs, Src/Plugins/Tests.Security/Validators/SEC101_025.SendGridApiKeyValidatorTests.cs, Src/ReleaseHistory.md
- Refactoring validator using scopes API to retrieve the permissions
- Adding tests to increase code coverage
=> Improving SendGridApiKeyValidator

Src/Plugins/Security/SEC101_027.MailChimpApiKeyValidator.cs, Src/Plugins/Security/SEC101_033.MongoDbCredentialsValidator.cs, Src/Plugins/Security/SEC101_038.PostgreSqlCredentialsValidator.cs, Src/Plugins/Tests.Security/Helpers/HttpMockHelper.cs, Src/Plugins/Tests.Security/Validators/SEC101_027.MailChimpApiKeyValidatorTests.cs, Src/SarifPatternMatcher.runsettings
=> Adding MailChimpApiKey mock tests

Src/Plugins/Security/SEC101_017.NpmAuthorTokenValidator.cs, Src/Plugins/Tests.Security/Validators/SEC101_017.NpmAuthorTokenValidatorTests.cs
Simply updates the test to no longer use anonymous types.
=> Update NPM Author Token to new struct

Src/ReleaseHistory.md
=> Updating release history

Src/ReleaseHistory.md, version.json
=> Preparing release

Src/Plugins/Tests.Security/Helpers/HttpMockHelper.cs, version.json
Small change to improve readability of test code I'm looking at frequently.
=> Style change

Src/Plugins/Security/SEC101_015.AkamaiCredentialsValidator.cs, Targets/build.common.props
- Using the latest NetAnalyzers package
- Fixing style warning
=> Updating NetAnalyzers package

Src/ReleaseHistory.md, version.json
- Updating the release history and version files.
=> Preparing Release v1.9.0

Src/ReleaseHistory.md, version.json
=> Prepare release v1.10.0

CONTRIBUTING.md, docs/getting-started/DebuggingGuide.md
Added specific spectre libraries to install in the DebuggingGuide.md, and clarified steps to take for first commit in Contributing.md
This is a docs update. No release history or tests update.
=> Onboarding documents clarification updates.

Src/Sarif.PatternMatcher/SearchSkimmer.cs, docs/DebuggingGuide.md
@marmegh @cfaucon @daniellegonzalez @HulonJenkins 
I am pushing this docs only change directly into the tree. Whoever is interested, please 'test' the updated debugging guide by attempting to follow it (and put any revisions to the guide that you may have in PR). 
Thanks!
=> Update debugging guide. Document first interesting breakpoint.

docs/DebuggingGuide.md
@cfaucon @marmegh @priyankabhaskar @HulonJenkins
=> Update debugging guide.

docs/DebuggingGuide.md
Updating debugging document based on usage with Visual Studio 2022 IDE.
=> Updating debugging document based

.github/CODEOWNERS
This change will require the CodeOnwers to approve independent of the file path.
=> Fixing CODEOWNERS

Src/.editorconfig, Src/Sarif.PatternMatcher/SearchSkimmer.cs
Silenced warning SA1307 - static variables should start with upper case letters
Suggested (instead of silenced) warning SA1602 - Enumeration Documentation
Fixed warning SA1505 curly braces in SearchSkimmers.cs
Fixed warning SA1204 static before non static in SearchSkimmers.cs
=> Fixed or Silenced build warnings

Src/Plugins/Tests.Security/EndToEndTests.cs, Src/Test.UnitTests.Sarif.PatternMatcher/PatternInvariantTests.cs
Improve test ability to locate validators file.
Improve test output (which should be put into a common helper in Test.Utilities at some point).
=> Test infrastructure updates.

Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_044.NpmCredentialsValidator.cs, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_044.NpmCredentials.sarif, Src/Sarif.PatternMatcher/AnalyzeCommand.cs, Src/Test.UnitTests.Sarif.PatternMatcher/PatternInvariantTests.cs
Our NPM detection used the old analysis model. This PR converts it to our newer, intrafile regex form.
=> Npm credentials intrafile analysis

Src/Test.UnitTests.Sarif.PatternMatcher/PatternInvariantTests.cs
More robust invariant testing. Added/Edited functions to handle more test cases mostly involving ruleID checking with rule definitions in JSON and with filenames. Also added backwards checks to validator -> tests function.
Now checks that a rule name _and_ ID are consistent in validator and test filenames
Now checks for rules with multiple conflicting rule IDs
Now checks for rule IDs with multiple conflicting rule names
Now checks that all tests have validators as well as all validators have tests.
=> More Robust Invariant Testing

Src/ReleaseHistory.md
=> Update SARIF SDK to 5f58c97825c842dc1f90b59c126198d0f9db62e6

Src/Plugins/Tests.Security/Helpers/HttpMockHelper.cs
Update is simply to accept some new test helpers, no behavioral changes in product.
=> Update SARIF SDK to commit 2c066f756d2abd84c8c093a3ab3395623d398099

Src/SarifPatternMatcher.sln
This change is updating sarif-sdk submodule to commit: 696ea3714082a6035dda7c6e51c02e2bcbc280d1.
No changes were made in the release notes because there is no impact on customers.
=> Updating sarif-sdk submodule to enable Test.UnitTests.Sarif

Src/ReleaseHistory.md
@cfaucon, pulls in context region population fix for API-driven scenarios.
=> Update spam latest

Src/Sarif.PatternMatcher/AnalyzeCommand.cs
=> Stop JSON logical processing when we have an empty results list.

.github/workflows/codeql-analysis.yml
This PR makes the following changes:
1. Removes the schedule for running CodeQL jobs.
2. Prints out the disk usage immediately after the SARIF Pattern Matcher build, for diagnostic purposes.
=> Disk space failure analytics

Src/Plugins/Security/SecurePlaintextSecretsValidators/NpmAuthorTokenHelper.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_001.HttpAuthorizationRequestHeaderValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_004.FacebookAppCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_005.SlackApiKeyValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_007.GitHubAppCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_010.SquarePatValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_011.SquareCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_012.SlackWebhookValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_015.AkamaiCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_018.TwilioCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_020.DropboxAccessTokenValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_021.DropboxAppCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_025.SendGridApiKeyValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_026.MailgunApiCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_027.MailChimpApiKeyValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_029.AlibabaCloudCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_035.CloudantCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_043.NuGetCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_044.NpmCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_045.PostmanApiKeyValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_046.DiscordApiCredentialsValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_047.CratesApiKeyValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_048.SlackWorkflowKeyValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_049.TelegramBotTokenValidator.cs, Src/Plugins/Security/SecurePlaintextSecretsValidators/StripeApiKeyValidatorBase.cs, Src/Sarif.PatternMatcher.Sdk/ExtensionMethods.cs
- Add a new `HttpClient` extension method for `GetAsync()` method.
- Apply changes replacing current HttpClient call with `ReadResponseHeaders` extension method.
=> Add a new `HttpClient` extension method and apply the changes to existing code

Src/Test.UnitTests.Sarif.PatternMatcher/PatternInvariantTests.cs
Rename Backend to MicrosoftOnly. Can this test be moved into SPMI? 
=> pattern invariant backend rename

Src/Sarif.PatternMatcher.Sdk/ExtensionMethods.cs, Src/Test.UnitTests.Sarif.PatternMatcher.Sdk/ExtensionMethodTests.cs
Create ContainsDigitLowercaseAndUppercaseLetter() Extension method made of other methods, and add proof to it.
Create unit tests for these extension methods.
=> Create ContainsDigitLowercaseAndUppercaseLetter Helper with proof

ReleaseHistory.md, Src/Sarif.PatternMatcher.Sdk/Fingerprint.cs, version.json
=> Query string added to fingerprint

ReleaseHistory.md, Src/Sarif.PatternMatcher.Sdk/Fingerprint.cs, version.json
Update sarif-sdk submodule.
Add PR to ReleaseHistory.
=> Update Sarif-sdk submodule.

ReleaseHistory.md, Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs, version.json
Resolves a null deref on attempting to hash null file contents.
=> Changes for 4.3.10

ReleaseHistory.md, Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json, Src/Plugins/Security/Security.SharedStrings.txt, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_047.CratesApiKey.sarif
Disable `SEC101/047.CratesApiKey` which has broken dynamic validator generating noises.
=> Update CratesApiKey regex and disable it temporarily.

Src/RE2.Managed/NativeMethods.cs, Src/RE2.Managed/RE2.Managed.csproj
=> Update libre2 references to so file.

ReleaseHistory.md, version.json
Actually update submodule and change version to v4.5.7
=> Actually Update submodule. v4.5.7

ReleaseHistory.md, Src/Plugins/Security/Security.csproj, azure-pipelines.yml
Fix `error : You must install or update .NET to run this application.` in pipeline
current main screenshot:
`error : You must install or update .NET to run this application. [D:\a\1\s\Src\Sarif.PatternMatcher.Function\Sarif.PatternMatcher.Function.csproj::TargetFramework=net6.0]`
Update: also updated SDK submodule.
=> Fix `error : You must install or update .NET to run this application.`

ReleaseHistory.md, Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_044.NpmCredentialsValidator.cs, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_044.NpmCredentials.sarif, Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_044.NpmCredentials.ps1
[ICM issue fix] Remove the secret format assumption for rule 044 NpmCredentials
=> [ICM issue fix] Remove the secret format assumption for rule 044 NpmCredentials

ReleaseHistory.md, version.json
@HulonJenkins @cfaucon @suvamM
=> Release v4.6.0.

docs/DebuggingGuide.md, docs/UsingClientTool.md
=> Fix the wrong parameters used in the doc
