microsoft/sarif-pattern-matcher

- Src/Plugins/BannedApi/BannedApi.csproj
- Src/Plugins/BannedApi/build/BannedApi.targets
- Src/Plugins/BannedApi/tools/Init.ps1
Below a generic script using `.targets` to move content from the package to somewhere else:
```xml
<Target Name="CopyScriptsToProject" BeforeTargets="Build">
<Message Text="Copying scripts to project" />
<ItemGroup>
<SourceScripts Include="$(MSBuildThisFileDirectory)..\content\**\*.*"/>
</ItemGroup>
<Copy SourceFiles="@(SourceScripts)" DestinationFiles="@(SourceScripts -> '$(MSBuildProjectDirectory)\content\%(RecursiveDir)%(Filename)%(Extension)')" />
</Target>
<Target Name="CopyUtilityScriptToProject" BeforeTargets="Build">
<Copy SourceFiles="$(MSBuildThisFileDirectory)..\content\file" DestinationFiles="$(MSBuildProjectDirectory)\content\file" />
</Target>
```
> BannedApi will move content to .spam in root source folder

- Src/Plugins/Security/Properties/AssemblyInfo.cs
- Src/Plugins/Tests.Security/Validators/AzureDevOpsPersonalAccessTokenValidatorTests.cs
- Src/RE2.Managed/Regex2.cs
- Src/Sarif.PatternMatcher.Benchmark/Benchmarks/AnalyzeCommandBenchmarks.cs
- Src/Sarif.PatternMatcher.Benchmark/Program.cs
- Src/Sarif.PatternMatcher.Benchmark/Sarif.PatternMatcher.Benchmark.csproj
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/Sarif.PatternMatcher.csproj
- Src/Sarif.PatternMatcher/ValidatorsCache.cs
- Src/SarifPatternMatcher.sln
- Src/Test.UnitTests.RE2.Managed/Regex2Tests.cs
- Src/Test.UnitTests.Strings.Interop/String8Tests.cs
- azure-pipelines.yml
- Added more tests, which increased our coverage from 76% to 90.5%
- Changed the method `CreateSkimmersFromDefinitionsFiles` to accept the engine, so the user could choose to use `DotNetRegex,` `CachedRegex` or `RE2Regex`
- Added a benchmark project so we can always take a look and compare our different regex providers.
Below a snippet:
|                                         Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------------------- |---------:|----------:|----------:|------:|------:|------:|----------:|
|       AnalyzeCommand_SimpleAnalysisDotNetRegex | 3.681 ms | 0.1905 ms | 0.5496 ms |     - |     - |     - |  70.98 KB |
| AnalyzeCommand_SimpleAnalysisCachedDotNetRegex | 4.682 ms | 0.0931 ms | 0.2533 ms |     - | …
> Adding more tests

- Src/Plugins/ValidatorBase.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
@eddynaka @cfaucon 
We weren't actually persisting fingerprints properly, now fixed. Also, the 'unauthorized' helper omitted the '#' delimiter, with the result that these issues were elevated to error (because the validator output could not be parsed).
We need to make this condition produce a useful error! Probably any result in these circumstances s/be dropped to a warning, I'll make that change soon.
> Fix fingerprint emit. Fix unauthorized reporting.

- Src/Plugins/Security/SEC1001.SecurePlaintextSecrets.json
- Src/Plugins/Security/SEC1004.UseSecureApi.json
- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Security/Security.csproj
- Src/Plugins/Security/build/Sarif.PatternMatcher.Security.targets
- Src/Plugins/ValidatorBase.cs
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/SearchDefinitions.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/SearchSkimmerTests.cs
@eddynaka 
This change provides a model for populating replacement strings directly from disk. This will allow us to store complex regular expressions without requiring any escaping. This will greatly facilitate developing complex patterns. :)
Also, we should switch to instantiating a skimmer *per rule*. We have a problem today, we support two models: one in which a definition refers to a single rule, with multiple match expressions. The other in which a parent definition flows common information to each match expression. This flexibility isn't serving us well. :) We'll talk more about cleaning it up. For now, I'm aggressively pushing inherited data (and replacing global strings) in match expressions before passing them to the skimmers...
> Push data to match expressions

- Src/.editorconfig
- Src/Plugins/Security/SEC101_006.GitHubPatValidator.cs
- Src/Plugins/Security/SEC101_045.PostgreSqlConnectionStringValidator.cs
- Src/Plugins/Security/SEC101_046.SqlConnectionStringValidator.cs
- Src/Plugins/Security/SEC101_047.MySqlConnectionStringValidator.cs
- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_046.SqlConnectionString.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_047.MySqlConnectionString.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_006.GitHubPat.ps1
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_046.SqlConnectionString.ps1
- Src/Plugins/ValidatorBase.cs
- Adding host/account/database/password limits based on docs.microsoft
- Adding ignoreList (this will reduce 1500 results)
- Adding more words to ignore in case it finds something in the matched pattern
- Checking if string is not null or whitespace before checking for letters and numbers, preventing a null reference
> Updating SqlConnectionString and GitHubPat validators

- Src/Sarif.PatternMatcher/SearchSkimmer.cs
@eddynaka 
Some unicode characters are escaped by URL.LocalPath. This breaks file reads. We can't simply URL decode these values, as some apparently URL decoded file names are actually valid on disk. The solution is to simply use the OriginalString provided to us originally by the file system.
> Unicode escaping

- Src/Plugins/Security/SEC101_001.HttpAuthorizationRequestHeaderValidator.cs
- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_001.HttpAuthorizationRequestHeader.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_001.HttpAuthorizationRequestHeader.ps1
- Src/Plugins/ValidatorBase.cs
This PR fixes the following issues:
- example.com and example.com/ should return the same fingerprint
- adding a dynamic validator
> Improvement in HttpAuthorizationRequestHeader validation

- Src/Plugins/Security/Security.csproj
- with this pr we will enable net472 support.
- for the previous package if we added to a netframework project, it wasn't moving the files correctly to the output folder
> enable net472 support

- Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json
- Src/Plugins/Security/SEC101_015.AkamaiKeyValidator.cs
- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_015.AkamaiKey.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_015.AkamaiKey.ps1
> Akamai validator

- Src/Plugins/Tests.Security/EndToEndTests.cs
@eddynaka 
Now if a notification is generated during end-to-end testing, the tests will fail. Nice!
> Enforce that no notifications are generated during file diff tests.

- Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json
- Src/Sarif.PatternMatcher.Cli/ExportRulesMetatadaCommand.cs
- Src/Sarif.PatternMatcher.Cli/ExportRulesMetatadaOptions.cs
- Src/Sarif.PatternMatcher/MatchExpression.cs
@eddynaka 
We need a mechanism to specify deprecated names. This information should actually be written out to SARIF logs! But as we know, it's very difficult now to configure that output in an already very complicated class.
For now, I've added a couple examples to the new export rules to markdown command. We should make two obvious improvements:
1) We should first go find all the recent rule name renames to make sure they are there. Note that we don't need to track every rule rename scrupulously. We really only require that we retrain the *last* changed rule name (to help with fingerprint breaks).
2) We should improve our export rules command to emit this data as SARIF! :) That would be easier for our data processing jobs to generate and parse. The markdown is trivial to parse but of …
> Deprecated name

- Src/RE2.Managed/Regex2.cs
- Src/RE2.Native/RE2Native.cpp
- Src/Test.UnitTests.RE2.Managed/Regex2Tests.cs
RE2 allows for optional capturing groups.
The way this is handled in RE2 is unexpected (to me at least) and was not explicitly documented in the header API, which is why I missed it.
RE2 reports a submatch with index=0 if the submatch is not found.
I did not explicitly handle that case in my code. This PR adds that handling.
> Fix handling of optional groups in RE2 wrapper

- Src/Plugins/Tests.SalModernization/TestData/UpdateSalToCurrentVersion/ExpectedOutputs/SEC105_001.AnalysisAssume.sarif
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
The interpretation will replace the current key if the key is a substring of current key
E.g.
$SEC105/003.post=[^\w_]__post[^\w_]
$SEC105/003.postinvalid=[^\w_]__post_invalid[^\w_]
$SEC105/003.postinvalid will be interpreted into "{$SEC105/003.post}invalid" = "[^\w_]__post[^\w_]invalid"
This is a fix for the case if another key is a substring of current key.
If need to fully support multiple keys (e.g. "$string1with$string11", may need to consider adding left/right boundaries to the key.
> Fix issue in shared string interpretation.

- Src/Sarif.PatternMatcher.Sdk/Fingerprint.cs
- Src/Sarif.PatternMatcher/ValidatingVisitor.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Sdk/FingerprintTests.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/ValidatingVisitorTests.cs
This change fixes the following exceptions:
```
ValidationError:'ArgumentOutOfRangeException' exception raised parsing potentially malformed fingerprint: '[host=[Azure_SQL_Server][Sql_Database_Dns_Suffix],1433][id=[Environment_Name]_{0}_login_{1}][platform=SqlOnPremise][resource=[Environment_Name]]'. Exception message: 'Specified argument was out of the range of valid values.
Parameter name: keyName'
Parameter name: fingerprintText   at Microsoft.CodeAnalysis.Sarif.PatternMatcher.Sdk.Fingerprint..ctor(String fingerprintText, Boolean validate)
at Microsoft.CodeAnalysis.Sarif.PatternMatcher.Sdk.Fingerprint.Merge(String previousFingerprintText)
at Microsoft.CodeAnalysis.Sarif.PatternMatcher.ValidatingVisitor.VisitResult(Result node)
ValidationError:'ArgumentException' exception raised …
```
> Fixing ArgumentException during ValidatingVisitor analysis

- Src/Plugins/Security/SEC101_005.SlackTokenValidator.cs
- Src/Plugins/Tests.Security/Validators/SEC101_005.SlackTokenValidatorTests.cs
* Converts `SlackTokenValidator` from using `WebClient` to `HttpClient`
* Adds Mock Http calls to `SlackTokenValidatorTests` to properly test all code paths.
> Create Mock Http tests for Slack Tokens

- Src/Plugins/Security/SEC101_001.HttpAuthorizationRequestHeaderValidator.cs
- Src/Plugins/Security/SEC101_004.FacebookAppCredentialsValidator.cs
- Src/Plugins/Security/SEC101_005.SlackTokenValidator.cs
- Src/Plugins/Security/SEC101_007.GitHubAppCredentialsValidator.cs
- Src/Plugins/Security/SEC101_010.SquarePatValidator.cs
- Src/Plugins/Security/SEC101_011.SquareCredentialsValidator.cs
- Src/Plugins/Security/SEC101_012.SlackWebhookValidator.cs
- Src/Plugins/Security/SEC101_015.AkamaiCredentialsValidator.cs
- Src/Plugins/Security/SEC101_016.StripeApiKeyValidator.cs
- Src/Plugins/Security/SEC101_017.NpmAuthorTokenValidator.cs
- Src/Plugins/Security/SEC101_018.TwilioCredentialsValidator.cs
- Src/Plugins/Security/SEC101_020.DropboxAccessTokenValidator.cs
- Src/Plugins/Security/SEC101_021.DropboxAppCredentialsValidator.cs
- Src/Plugins/Security/SEC101_026.MailgunApiCredentialsValidator.cs
- Src/Plugins/Security/SEC101_027.MailChimpApiKeyValidator.cs
- Src/Plugins/Security/SEC101_043.NuGetCredentialsValidator.cs
- Src/Plugins/Security/SEC101_044.NpmCredentialsValidator.cs
- Src/Plugins/Security/SEC101_045.PostmanApiKeyValidator.cs
- Src/Plugins/Security/SEC101_046.DiscordApiCredentialsValidator.cs
- Src/Sarif.PatternMatcher.Sdk/ValidatorBase.cs
@michaelcfanning , this is the change we talked yesterday at night.
We will have two httpclients, one that is static and one private.
The static will be normally used.
The private will **only** be used during tests.
> Making HttpClient static again when not using in tests

- Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json
- Src/Plugins/Security/SEC101_047.CratesApiKeyValidator.cs
- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_047.CratesApiKey.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_047.CratesApiKey.ps1
- Src/Plugins/Tests.Security/Validators/SEC101_047.CratesApiKeyValidatorTests.cs
- Src/Sarif.PatternMatcher.Sdk/AssetPlatform.cs
> Adding CratesApiKey validator

- Src/Plugins/Tests.Security/Validators/SEC101_044.NpmCredentialsValidatorTests.cs
NPM Credentials Validator now uses the same test struct as everyone else. 
> Moves NPM credentials to use the global HttpMockTests Struct

- Src/Plugins/Security/SEC101_012.SlackWebhookValidator.cs
- Src/Plugins/Tests.Security/Validators/SEC101_005.SlackTokenValidatorTests.cs
- Src/Plugins/Tests.Security/Validators/SEC101_012.SlackWebhookValidatorTests.cs
* Update Slack Token validator to use global `MockHttpTestCase` struct.
* Add mock validator for Slack Webhooks
> Improve Slack mock Tests

- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_033.MongoDbCredentials.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_033.MongoDbCredentials.ps1
- Src/ReleaseHistory.md
> Eliminate whitespace and commas from MongoDB match candidates (and resulting fingerprints).

- Src/RE2.Managed/Regex2.cs
- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
- Src/Sarif.PatternMatcher/ValidatorsCache.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/SearchSkimmerTests.cs
> Single match expression should run multiple regex types

- Src/Plugins/Tests.Security/Helpers/HttpMockHelper.cs
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_044.NpmCredentials.ps1
- Src/Plugins/Tests.Security/Validators/SEC101_044.NpmCredentialsValidatorTests.cs
- Src/ReleaseHistory.md
This change will enable us to mock `HttpResponseMessage` and it can also replace two fields in the future: `HttpContents` and `HttpStatusCodes`.
Current code coverage:
The new version achieves 100% of code coverage:
> Expanding HttpMockHelper to be able to mock HttpResponseMessage

- Scripts/BuildAndTest.ps1
- Src/SarifPatternMatcher.runsettings
- azure-pipelines.yml
- disabled previous code coverage that was relying on coverlet
- enabled code coverage in azure pipelines, showing how much we cover.
> Enabling native code coverage

- Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json
- Src/Plugins/Security/SEC101_004.FacebookAppCredentialsValidator.cs
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_004.FacebookAppCredentials.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_004.FacebookAppCredentials.ps1
- Src/Plugins/Tests.Security/Validators/SEC101_004.FacebookAppCredentialsValidatorTests.cs
- azure-pipelines.yml
- Required fields should not require `TryGetValue` call (this will throw the `KeyNotFound` exception if the key does not exist)
- Added `HelpUri` pointing to Facebook page with guidance
> Improving FacebookAppCredentials rule

- Src/Plugins/Security/SEC101_003.GoogleApiKeyValidator.cs
- Src/Plugins/Security/Security.csproj
Updating GoogleApi to latest version that uses a safe package of `Portable.BouncyCastle`:
https://github.com/bcgit/bc-csharp/wiki/CVE-2020-15522
> Fixing package vulnerability from GoogleApi

- version.json
Changing version to `1.8.0-alpha` since we are going to release the version `v1.7.0` from `release/v1.7.0`.
This will enable us to:
- always have the release/v1.7.0 branch to track
- easy to hotfix (we can start a branch from release/v1.7.0, make the fix, and ship)
> Updating version to 1.8.0-alpha

- Src/Plugins/Tests.Security/Validators/SEC101_007.GitHubAppCredentialsValidatorTests.cs
- Src/Plugins/Tests.Security/Validators/SEC101_046.DiscordApiCredentialsValidatorTests.cs
- Src/Plugins/Tests.Security/Validators/SEC101_047.CratesApiKeyValidatorTests.cs
- Src/ReleaseHistory.md
Updating the sarif-sdk submodule will enable us to expose three new parameters for the `analyze` command: `postUri`, `automationId`, and `automationGuid`.
Below is one example of the new command-line arguments:
```bash
❯ .\spam.exe analyze c:\temp\ -o c:\test.sarif --force -d C:\Rules.json --automationId "Test" --automationGuid BC6CCB9F-16C8-4656-A227-C7B5F34864FA --postUri http://localhost:7072/api/upload-content
```
> Exposing automationId, automationGuid, and postUri in the analyze command.

- Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json
- Src/Plugins/Security/SEC101_049.TelegramBotTokenValidator.cs
- Src/Plugins/Security/Security.SharedStrings.txt
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/ExpectedOutputs/SEC101_049.TelegramBotToken.sarif
- Src/Plugins/Tests.Security/TestData/SecurePlaintextSecrets/Inputs/SEC101_049.TelegramBotToken.ps1
- Src/Plugins/Tests.Security/Validators/SEC101_049.TelegramBotTokenValidatorTests.cs
- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher.Sdk/AssetPlatform.cs
This is a new rule which will look for telegram bot tokens. If any match is found, the dynamic validation will be able to check if this is still live or not, updating the `finngerprint.id` with the username of the bot if available.
> Adding telegram bot token validator

- Src/Plugins/Tests.Security/Validators/SEC101_001.HttpAuthorizationRequestHeaderValidatorTests.cs
Removing dummy test that was actually trying to connect and validate `www.host.com`. Since we have mock tests, this isn`t needed.
> Removing dummy test from HttpAuthorizationRequestHeaderValidatorTests

- Src/RE2.Native/RE2.Native.x64.vcxproj
- Src/RE2.Native/RE2.Native.x86.vcxproj
- Src/RE2.Native/re2.x64.vcxproj
- Src/RE2.Native/re2.x86.vcxproj
This change will allow us to use the latest windows SDK installed instead of hardcoding a specific version.
> Using latest windows SDK to compile RE2 libraries

- Src/Plugins/Security/Security.csproj
- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher.Function/Sarif.PatternMatcher.Function.csproj
- azure-pipelines.yml
This change will fix the following issues:
- Bump MongoDB.Driver from 2.13.1 to 2.15.0: fixes https://nvd.nist.gov/vuln/detail/CVE-2021-39208
- Microsoft.AspNetCore.Http from 2.1.0 to 2.2.0: fixes https://nvd.nist.gov/vuln/detail/CVE-2020-1045
As you can see, you cannot see Microsoft.AspNetCore.Http version 2.1.0 in the changes because it is a reference from the package Microsoft.NET.Sdk.Functions -> Microsoft.Azure.WebJobs.Extensions.Http -> Microsoft.AspNetCore.Http
> Bump MongoDB.Driver from 2.13.1 to 2.15.0 and Microsoft.AspNetCore.Http from 2.1.0 to 2.2.0

- Src/ReleaseHistory.md
This change will update the ReleaseHistory file, adding the Url rule that was developed in the PR #611
> Adding Url rule to ReleaseHistory

- Src/Plugins/Tests.AzureDevOpsConfiguration/AZC101.BuildDefinitionSecurityTests.cs
- Src/Plugins/Tests.AzureDevOpsConfiguration/AZC102.ServiceConnectionSecurityTests.cs
- Src/Plugins/Tests.AzureDevOpsConfiguration/EndToEndTestsAzureDevOpsConfiguration.cs
- Src/Plugins/Tests.SalModernization/EndToEndTestsSalModernization.cs
- Src/Plugins/Tests.SalModernization/SEC105.UpdateSalToCurrentVersion.cs
- Src/Plugins/Tests.Security/EndToEndTests.cs
- Src/Plugins/Tests.Security/SEC101.SecurePlaintextSecretsTests.cs
- Src/Plugins/Tests.Security/SEC102.ReviewPotentiallySensitiveDataTests.cs
- Src/Plugins/Tests.Security/SEC103.ReviewPotentiallySensitiveFilesTests.cs
- Src/Plugins/Tests.Security/SEC104.UseSecureApiTests.cs
- Src/ReleaseHistory.md
- Src/Test.UnitTests.Sarif.PatternMatcher.Cli/AnalyzeCommandTests.cs
This change will update the sarif sdk submodules to point to the latest released that we made (2.4.15).
Here you can find the difference between the submodules change:
https://github.com/microsoft/sarif-sdk/compare/b2c7e399cfaf1fde47b336bbb4976f723263efa3...9f0eed7549736b28d59a2e93f443ba47e3bd978e
> Updating sarif.sdk submodules

- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher.Cli/ImportAndAnalyzeOptions.cs
- Src/Sarif.PatternMatcher.Cli/Program.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Cli/AnalyzeCommandTests.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Cli/ProgramTests.cs
This change enables response file processing as provided by the driver framework. This change additionally enables a behavior previously requested by the Guardian team: to provide a zero (success) result code when a user initiates any valid command. Currently, due to our specific use pattern for CommandLibrary, the tool returns a result code of '1' on any help command. 
After this change, any argument prefixed with the '@' will interpreted as a file name. That file, if it exists, will be loaded. Each line in that file will be expanded into an argument that will be injected into the command-line (for example all env vars will be expanded).
spam.exe @MyResponseFile.rsp
The driver code for the argument expansion is in the Sarif Driver …
> Enable response file parsing in driver.

- Src/Sarif.PatternMatcher.Cli/Program.cs
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/AnalyzeOptions.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Cli/AnalyzeCommandTests.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs
I previously added a new helper to the SARIF Driver SDK to report out when no plugins are configured. Today it occurred to me that the right fix is simply to make this command-line argument required. Oops. So let's review this change and then I'll go rip out that other helper again. 
The heart of this change is simply to add `Required = true` to the `OptionAttribute` backing the search definitions argument. I've added a unit test. This change includes a useful test method I intend to exercise later.
Also, I've incidentally updated SARIF-SDK submodule.
> Make search definitions argument required.

- Src/Plugins/Security/Security.csproj
- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher.Sdk/Sarif.PatternMatcher.Sdk.csproj
- Src/Sarif.PatternMatcher/Sarif.PatternMatcher.csproj
This change will allow us to create packages using stable versions that we already released.
Current behavior: Every new package requires a new version of RE2 and Strings.Interop.
New behavior: Every new package will require version 1.10, which is the last version that we released.
To be able to run this tool and the legacy version side by side, both tools need to use the same references. We cannot have a moving reference because it will generate an exception when loading the second binary (FileNotFound due to binary version mismatch).
Referencing the old style and testing the new style of the package to see if everything works.
> Creating stable references of RE2 and Strings.Interop when packing binaries

- .github/workflows/codeql-analysis.yml
Updating CodeQL Action from v1 to v2.
- Sometimes, CodeQL is throwing exceptions
- CodeQL Action v1 will be deprecated on December 7th, 2022.
> Updating codeql to v2

- Src/Plugins/Security/Security.csproj
- Src/ReleaseHistory.md
This change will update the `Microsoft.Security.Utilities` to the version 1.3.0, which is used in the legacy version as well.
No changes in the product.
The difference between packages: https://github.com/microsoft/security-utilities/compare/v1.1.0...v1.3.0.
> Updating Microsoft.Security.Utilities to 1.3.0

- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher/AnalyzeContext.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/SearchSkimmerTests.cs
Initial implementation of the maximum file size value defaulted to -1 when not set, this now defaults to 0 and  has resulted in some false negatives.
Updated `SearchSkimmer.DoesTargetFileExceedSizeLimits` to use a new default `MaxFileSizeInKilobytes` (roughly equivalent to 10MB). Expanded test coverage to prevent regression.
> Fix false negative when max file size is not set

- Src/Plugins/Tests.Security/EndToEndTests.cs
- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher.Cli/Sarif.PatternMatcher.Cli.csproj
- Src/Sarif.PatternMatcher.Sdk/Sarif.PatternMatcher.Sdk.csproj
- Src/Sarif.PatternMatcher/Sarif.PatternMatcher.csproj
This change will align the newtonsoft.json package to be the same as internal references.
Consumers of the library must use a more secure version (13.0.1).
It also changes the Sarif.PatternMatcher projects to depend on RE2.Managed/Strings.Interop package to prevent some warnings when building in the cmd/vs.
> Aligning package reference

- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs
We now look for any definitions file, by name, in the binary execution directory.
@cfaucon
> Loosen probing logic to look for files directly alongside client exe.

- Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_044.NpmCredentialsValidator.cs
@eddynaka, this was one you created a while back. the backing registry appears to be deactivated and the result is that the validation fails on the anonymous access check (which simply returns S_OK).
Can you please work with @marmegh or @HulonJenkins to demonstrate how to revive this test asset?
> Offline test credential in secret manager has expired.

- Src/Sarif.PatternMatcher.Sdk/StaticValidatorBase.cs
- Src/Sarif.PatternMatcher.Sdk/ValidatorBase.cs
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Sdk/StaticValidatorBaseTests.cs
Introduce a new helper that prevents inadvertent match against base64-encoded strings which encode text strings rather than random sequences of bytes.
We could use a unit-test for this. Anyone want to jump in?
> Add base64-encoding helper to assist with certain credential FP elimination.

- Src/Test.UnitTests.Sarif.PatternMatcher/PatternInvariantTests.cs
1. Added Filename test to see if they exactly match JSON rule definition
2. Added more extensive regex checking in Shared Strings
3. Added SharedStrings -> JSON test to complement JSON -> SharedString test
4. Updated consistency of loading searchDefinitions
TODO:
Still need to create a PR for Spmi where I update SEC101.SecurePlaintextSecretsPushProtectionTests.cs to actually call these tests.
> Exact filenames based on JSON

- Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_044.NpmCredentialsValidator.cs
@HulonJenkins @marmegh 
A simple change to handle the transient condition of returning 'forbidden' from the NPM credentials check.
Observed empirically. Someone should mock this circumstance out soonish. :)
> Update status codes to convert 'forbidden' to unauthorized.

- Src/ReleaseHistory.md
- Src/Sarif.PatternMatcher.Cli/Sarif.PatternMatcher.Cli.csproj
Updating the executable and dotnet library name of the cli from spam to Sarif.PatternMatcher.Cli.
> Updating spam to Sarif.PatternMatcher.Cli.

- Src/Sarif.PatternMatcher.Sdk/Sarif.PatternMatcher.Sdk.csproj
- Src/Sarif.PatternMatcher/Sarif.PatternMatcher.csproj
Swapped RE2.Managed from Package Reference to Project Reference.
Swapped Strings.Interop from Package Reference to Project Reference.
We had the projects but were using NuGet packages instead. Removed the NuGet packages and added reference to projects.
> RE2.Managed & Strings.Interop Package -> Project References.

- Src/RE2.Native/RE2.Native.x64.vcxproj
- Src/RE2.Native/RE2.Native.x86.vcxproj
- Src/RE2.Native/re2.x64.vcxproj
- Src/RE2.Native/re2.x86.vcxproj
FYI, upgrading RE2 compilation with the result that we will now require VS2022 to compile.
You will need to install the 14.3 Spectre-enabled c runtime libraries for x64/x86 if you haven't.
> Update RE2 compilation to VS2022 target tools, 14.3

- Src/Test.UnitTests.Sarif.PatternMatcher/PatternInvariantTests.cs
Updated PatternInvariantTests to pull shared strings file from the field located in the json file. This ensures that the shared strings file that will be used is the one being checked. Before the shared strings file was passed in separately and could pass tests, while not actually being the file that the json would reference.
Also updated to loop through json files since there are now 2.
> PatternInvariantTest with 2 Json Files

- Src/RE2.Native/RE2Native.cpp
Will follow up with RE2 to propose lowering this to warning.
@eddynaka
> Disable DFA oom error as scary. 

- ReleaseHistory.md
- Src/Test.UnitTests.RE2.Managed/Test.UnitTests.RE2.Managed.csproj
- Src/Test.UnitTests.Sarif.PatternMatcher.Cli/Test.UnitTests.Sarif.PatternMatcher.Cli.csproj
- Src/Test.UnitTests.Sarif.PatternMatcher.Function/Test.UnitTests.Sarif.PatternMatcher.Function.csproj
- Src/Test.UnitTests.Sarif.PatternMatcher.Sdk/Test.UnitTests.Sarif.PatternMatcher.Sdk.csproj
- Src/Test.UnitTests.Sarif.PatternMatcher/ExtensionMethodsTests.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/Test.UnitTests.Sarif.PatternMatcher.csproj
- Src/Test.UnitTests.Strings.Interop/Test.UnitTests.Strings.Interop.csproj
Update xunit package reference to version 2.4.2.
Update FluentAssertions package reference to version 6.9.0.
Updated test using FluentAssertions to explicitly cast to string, since FluentAssertions no longer implicitly cast. Learned from https://github.com/microsoft/sarif-sdk/pull/2608
> Update xunit and FluentAssertions dependencies

- ReleaseHistory.md
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/MatchExpression.cs
- Src/Sarif.PatternMatcher/SearchDefinition.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
Add functionality to disable a rule in json file. By adding RuleEnabledState = "Disabled", the rule will not run any analysis. Future efforst will have this same field determine failure level since those fields are included in the RuleEnabledState enum.
> Initial matchexpression rule disable stub

- ReleaseHistory.md
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/AnalyzeContext.cs
- Src/Sarif.PatternMatcher/AnalyzeOptions.cs
Update SARIF SDK to 53b0246 to obtain version control provenance in options and context.
> SARIF SDK update for version control provenance.

- ReleaseHistory.md
- Src/Sarif.PatternMatcher.Cli/AnalyzeDatabaseCommand.cs
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/AnalyzeContext.cs
- Src/Sarif.PatternMatcher/AnalyzeOptions.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Cli/AnalyzeCommandTests.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs
- version.json
- DEP: Update SARIF SDK submodule from [53b0246 to 6c5825c](https://github.com/microsoft/sarif-sdk/compare/53b0246..6c5825c). [Full SARIF SDK release history](https://github.com/microsoft/sarif-sdk/blob/6c5825c/src/ReleaseHistory.md). Adds version control provenance.
- BRK: SARIF SDK update changes `--automationId` and `--automationGuid` command-line arguments to `--automation-id` and `--automation-guid`. [#732](https://github.com/microsoft/sarif-pattern-matcher/pull/732)
- BRK: `--search-definitions`/`-s` argument deprecated in favor of `plugin`/`-p`. [Full SARIF SDK release history](https://github.com/microsoft/sarif-sdk/blob/6c5825c/src/ReleaseHistory.md). Adds version control provenance.
- BUG: Resolve bug where console failed to emit `Note` messages. …
> Update to various renames for plugin arg, automation id and guid.

- ReleaseHistory.md
- Src/Sarif.PatternMatcher/AnalyzeCommand.cs
- Src/Sarif.PatternMatcher/AnalyzeOptions.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/AnalyzeCommandTests.cs
- BUG: We do not flow `--redact-secrets` argument properly to analysis. [#746](https://github.com/microsoft/sarif-pattern-matcher/pull/746)
- NEW: All `AnalyzeOptions` properties now settable. [#746](https://github.com/microsoft/sarif-pattern-matcher/pull/746)
> Set redact secrets via workaround until we get a driver framework fix.

- ReleaseHistory.md
- Src/Sarif.PatternMatcher/Sarif.PatternMatcher.csproj
- version.json
- BUG: Remove unnecessary `Test.Utilities.Sarif` reference from `Sarif.PatternMatcher` project. This test binary isn't built into our tool NuGet package and the erroneous reference causes missing file messages in some contexts.
@Jeremiah-Johnson @suvamM
> Remove test dependency

- Src/Sarif.PatternMatcher.Sdk/Crc32.cs
- Src/Test.UnitTests.Sarif.PatternMatcher.Sdk/Crc32Tests.cs
The static validator of Yandex Cloud Iam Access Secret needs to use Castagnoli's polynomial in Crc32 checksum computation.
This change expands the Crc32 class by adding support for Castagnoli's polynomial without affecting the existing public methods and their reference. 
The default crc32 polynomial will be IEEE polynomial.
> Expand the Crc32 class by adding support for Castagnoli's polynomial

- Src/Sarif.PatternMatcher/SearchSkimmer.cs
Various recent activities have the following pattern: we consume the JSON plug-in, and parse the regular expressions. The typical way to do this is to deserialize the JSON into a `SearchDefinitions` object, and then access the `MatchExpressions` list. However, this logic already exists in the `CreateSkimmersFromDefinitions` method, which creates a set of `Skimmer` objects. The problem: the match expressions were private.
This PR exposes the `MatchExpression` set as `public` in the `SearchSkimmer` class. 
```
ISet<Skimmer<AnalyzeContext>> skimmers = CreateSkimmersFromDefinitions(pluginsPath);
foreach (Skimmer<AnalyzeContext> skimmer in skimmers)
{
var ss = (SearchSkimmer)skimmer;
var regex = ss.MatchExpression.ContentsRegex;
}
```
> Exposing MatchExpressions in SearchSkimmer

- ReleaseHistory.md
- Src/Plugins/Security/SecurePlaintextSecretsValidators/AwsHttpRequestSigner.cs
- Src/Plugins/Security/SecurePlaintextSecretsValidators/SEC101_008.AwsCredentialsValidator.cs
- Src/Plugins/Security/Security.csproj
- Src/Plugins/Tests.Security/SecurePlaintextSecretsValidators/AwsHttpRequestSignerTests.cs
- Src/Plugins/Tests.Security/SecurePlaintextSecretsValidators/SEC101_008.AwsCredentialsValidatorTests.cs
- Src/Sarif.PatternMatcher/ValidatorsCache.cs
- Src/SarifPatternMatcher.sln
Updated `SEC101/008.AwsCredentials` validator to validate AWS access key/access secret using signed HTTP request.
- Get ride of AWS SDK dependencies
- Validate by calling AWS iam REST API using HTTP request with AWS signature V4 format.
- Parse the XML response instead of using SDK data model.
> Remove AWSSDK dependencies and refactor AwsCredentials validator to use HTTP request instead

- Src/RE2.Managed/FlexMatchValueComparer.cs
- Src/RE2.Managed/IronRE2Regex.cs
Update region computation for IronRE2. We need new unit tests that flag patterns that themselves contain unicode characters.
> Update region computation for matches that contain unicode chars.

- Src/Plugins/Security/Security.csproj
The previous version change (from 6.2.1 to 6.5.0) will cause build error for other projects referenced `sarif-pattern-matcher` due to `System.Threading.Channels` version conflicts.
> Restore package `RabbitMQ.Client` back to 6.2.1

- ReleaseHistory.md
- Src/Plugins/Security/SEC101.SecurePlaintextSecrets.json
- Src/Sarif.PatternMatcher/Base64EncodingMatch.cs
- Src/Sarif.PatternMatcher/MatchExpression.cs
- Src/Sarif.PatternMatcher/SearchSkimmer.cs
- Src/Test.UnitTests.Sarif.PatternMatcher/SearchSkimmerTests.cs
This is a breaking change, the rules with `MatchLengthToDecode` property set will break.
The solution is to replace it with `Base64EncodingMatch` property.
E.g. The rule definition
```
{
"Id": "SEC101/102",
"Name": "AdoPat",
"MatchLengthToDecode": 52,
"ContentsRegex": "$SEC101/102.AdoPat",
...
},
```
Need to be updated to
```
{
"Id": "SEC101/102",
"Name": "AdoPat",
"Base64EncodingMatch": { "MinSourceLength": 52, "MaxSourceLength": 52 },
"ContentsRegex": "$SEC101/102.AdoPat",
...
},
```
- Removed `MatchLengthToDecode` int property from `SearchSkimmer` class.
- Using a new class `Base64EncodingMatch` to present the decoded string length range.
- Updated existing rules using `MatchLengthToDecode` to `Base64EncodingMatch`.
- Unit tests added.
> Support detecting Base64 string from strings of specific length range
